### ISSUE TITLE
Add BufferGeometry support?

### ISSUE THREAD

**Issue by Ben-Mack** [drawcall/threejs-mesh-modifiers#1]
Thanks for this great library!

But look like this lib hasn't supported `BufferGeometry` yet, please add support for it because it comes with many benefits and is recommended to use in Three.js. 

In my case, using `TextBufferGeometry` decrease text creation time up to more than 4 times compare to `TextGeometry` ( from 4s to below 1s )

**Comment by looeee** [comment]
@Ben-Mack you're asking for a big update here - looking through the source code basically the whole library would have to be rewritten. I would say that the better approach would be to fork the library and create a new version that supports `BufferGeometry` yourself, if you have time or interest.

**Comment by Ben-Mack** [comment]
@looeee Thanks for your reply! Currently I don't need this lib to working with BufferGeometry, but I need to export the result of it `THREE.Geometry` to Glb for Facebook.

As I described here: https://github.com/mrdoob/three.js/issues/13397#issuecomment-369502128 `THREE.Geometry` converted to `BufferGeometry` then export to GLB got below problem on Facebook:

> Vertex COLOR_0 attributes of type RGB are (temporarily) not supported. They must be RGBA

Then as mrdoob reply at https://github.com/mrdoob/three.js/issues/13397#issuecomment-369726063 , I thought it will be just a quick fixes on Three.js library?

**Comment by looeee** [comment]
> Vertex COLOR_0 attributes of type RGB are (temporarily) not supported. They must be RGBA

As they say, it's temporary. Facebook's support of glTF is very new and not complete yet.

To clarify, this is not an issue wth three.js, it's an issue that Facebook needs to fix. 

In the meantime, perhaps you can remove the color attribute from your geometry before exporting?

**Comment by mjmaurer** [comment]
Did anyone end up forking? Three r125 defaults to BufferedGeometry for all *Geometry classes [1]. Might be a nice thing to add to the README as well.

[1] - https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

**Comment by drawcall** [comment]
The latest version of threejs-mesh-modifiers already supports BufferGeometry, because three.js removes THREE.Geometry
